package com.adi.practiceone.model

data class Product(
    val active: Boolean,
    val assurance: Boolean,
    val brand: Boolean,
    val category: String,
    val category_id: Int,
    val city: String,
    val condition: String,
    val courier: List<String>,
    val created_at: String,
    val desc: String,
    val favorited: Boolean,
    val for_sale: Boolean,
    val id: String,
    val images: List<String>,
    val name: String,
    val price: Int,
    val province: String,
    val rating: Rating,
    val seller_avatar: String,
    val seller_id: Int,
    val seller_name: String,
    val seller_negative_feedback: Int,
    val seller_positive_feedback: Int,
    val seller_term_condition: String,
    val seller_username: String,
    val sold_count: Int,
    val stock: Int,
    val top_merchant: Boolean,
    val url: String,
    val view_count: Int,
    val weight: Int
)